;MOHAMED THARWAT SHAWKY
.MODEL SMALL
.STACK
.DATA
PRINTST DB 'ENTER START NUMBER (2 DIGITS)','$'
PRINTEN DB 'ENTER END NUMBER (3 DIGITS)','$'
START DW ?
FNSH DW ?
TEN DW 10
Y DB 10
Y2 DW 100
.CODE
    MAIN PROC FAR
    .STARTUP
    ;PRINT START STATEMENT
    LEA DX,PRINTST
    MOV AH,09H
    INT 21H
    CALL NL
    ;READ START NUMBER (2 DIGITS)
    CALL READNUM
    MUL Y
    MOV BL,AL
    CALL READNUM
    ADD AL,BL
    SUB AL,10H
    MOV AH,00
    MOV START,AX
    CALL NL
    ;PRINT END STATEMENT
    LEA DX,PRINTEN
    MOV AH,09H
    INT 21H
    CALL NL
    ;READ END NUMBER (3 DIGITS)
    CALL READNUM
    MOV AH,00
    MUL Y2
    MOV BX,AX
    CALL READNUM
    MOV AH,00
    MUL Y
    ADD BX,AX
    CALL READNUM
    MOV AH,00
    ADD AX,BX
    SUB AX,14D0H
    ;CHECK SMALLEST NUMBER TO START WITH IT
    CMP START,AX
    JL O
    XCHG START,AX
O:
    SUB AX,START
    INC AX
    MOV CX,AX
    
    CALL NL
    MOV BX,0
DO:
    MOV AX,START
B:
    MOV DX,00
    DIV TEN
    PUSH DX
    INC BX
    CMP AX,0
    JNE B
A:
    POP DX
    CALL PRINTNUM
    DEC BX
    CMP BX,0
    JNE A
    INC START
    CALL TAP
    LOOP DO
    
    .EXIT
    
    MAIN ENDP
    
    PRINTNUM PROC NEAR
    MOV AH,02
    ADD DL,30H
    INT 21H
    RET
    PRINTNUM ENDP
    READNUM PROC NEAR
    MOV AH,01
    INT 21H
    RET
    READNUM ENDP
    TAP PROC NEAR
    MOV DX,9
    MOV AH,02
    INT 21H
    RET
    TAP ENDP
    NL PROC NEAR
    MOV DX,10
    MOV AH,02
    INT 21H
    RET
    NL ENDP
END MAIN
